#!/usr/bin/python
#coding: UTF-8
import argparse
import os
import sys
from collections import OrderedDict

os.environ['SEAFILE_CONF_DIR'] = "."

from seafobj.utils.ceph_utils import ioctx_set_namespace
from seafobj.backends.ceph import CephConf, IoCtxPool

obj_types = ['fs', 'commits', 'blocks']


def write_obj_to_fs(base_path, objtype, repo, obj_id, data):
    objpath = os.path.join(base_path, objtype, repo, obj_id[:2])
    path = os.path.join(objpath, obj_id[2:])
    if not os.path.exists(objpath):
        os.makedirs(objpath)
    with open(path, 'wb+') as f:
        f.write(data)


def main():
    # parse command line
    cmd_parser = argparse.ArgumentParser(
        description="copy objects from ceph backend to fs backend"
    )
    cmd_parser.add_argument("--client", "--id", "-i", dest="client",
                            default='seafile', help="ceph client id")
    cmd_parser.add_argument("--blocks-pool", "-b", dest="blocks",
                            default='seafile-blocks',
                            help="ceph pool containing block objects")
    cmd_parser.add_argument("--commits-pool", "-c", dest="commits",
                            default='seafile-commits',
                            help="ceph pool containing commit objects")
    cmd_parser.add_argument("--fs-pool", "-f", dest="fs",
                            default='seafile-fs',
                            help="ceph pool containing fs objects")
    cmd_parser.add_argument("--config", dest="config",
                            default='/etc/ceph/ceph.conf',
                            help="ceph.conf")
    cmd_parser.add_argument('--yes-i-really-really-want-to', dest="empty",
			    action="store_true",
                            help="Really delete all objects in the pools")
    cmd_parser.add_argument('-V', '--verbose', action="store_true",
                            dest="verbose",
                            help="Give detailed information, if possible")
    args = cmd_parser.parse_args()

    if not args.empty:
        print "You need to specify --yes-i-really-really-want-to to empty all of the following pools: %s" % (", ".join([args.commits, args.fs, args.blocks]))
        sys.exit(-1)

    conf = CephConf(args.config, args.commits, args.client)
    pool = IoCtxPool(conf)

    # get objects of all namespaces for every pool
    # commits first!
    ceph_pools = OrderedDict([('commits', args.commits),
                              ('fs', args.fs), ('blocks', args.blocks)])

    for objtype, poolname in ceph_pools.items():
        pool.conf.pool_name = poolname
        if args.verbose:
            print "Opening pool %s" % poolname
        ioctx = pool.create_ioctx()
        ioctx_set_namespace(ioctx, '\001')
        for obj in ioctx.list_objects():
            if args.verbose:
                print "removing object %s of ns %s" % (obj.key, obj.nspace)
            # set namespace for object
            ioctx_set_namespace(ioctx, obj.nspace)
            # delete object
            ioctx.remove_object(obj.key)

        ioctx.close()


if __name__ == '__main__':
    main()
